name: Generate Adblock Hosts

on:
  push:
    paths:
      - 'Regular Hosts.txt'
  workflow_dispatch:

jobs:
  convert-hosts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate hosts file
        run: |
          # Create header with custom content
          echo "# Ad Blocking Hosts File" > hosts
          echo "0.0.0.0 localhost" >> hosts
          echo "255.255.255.255 broadcasthost" >> hosts
          echo "::1 localhost" >> hosts
          echo "fe80::1%lo0 localhost" >> hosts
          echo "" >> hosts
          echo "0.0.0.0 ocsp.apple.com" >> hosts
          echo "::1 ocsp.apple.com" >> hosts
          echo "" >> hosts
          echo "###Facebook" >> hosts
          echo "#0.0.0.0 graph.facebook.com" >> hosts
          echo "#::1 graph.facebook.com" >> hosts
          echo "#0.0.0.0 external.xx.fbcdn.net" >> hosts
          echo "#0.0.0.0 scontent.xx.fbcdn.net" >> hosts
          echo "#::1 external.xx.fbcdn.net" >> hosts
          echo "#::1 scontent.xx.fbcdn.net" >> hosts
          echo "" >> hosts
          echo "# Google Amp" >> hosts
          echo "#cdn.ampproject.org" >> hosts
          echo "" >> hosts

          # Append processed entries from source file
          awk '{print "0.0.0.0 " $0}' "Regular Hosts.txt" >> hosts

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'Update adblock hosts file'
          add: hosts